#!/usr/bin/env node
/**
 * Fetches Lodestar lore atoms for all commits in a PR and posts/updates
 * a single comment on the PR.
 *
 * Environment variables required:
 *   LODESTAR_SERVER_URL  — e.g. https://lodestar.up.railway.app
 *   LODESTAR_API_KEY     — matches the server's LODESTAR_API_KEY
 *   LODESTAR_PROJECT_ID  — read from .lodestar/settings.json if not set
 *   GITHUB_TOKEN         — provided automatically by Actions
 *   GITHUB_REPOSITORY    — e.g. "tommyross/textdrop.sh"
 *   PR_NUMBER            — pull request number
 *   PR_COMMITS           — newline-separated list of commit SHAs
 */

import { readFileSync, existsSync } from "fs";

const COMMENT_MARKER = "<!-- lodestar-audit -->";

const serverUrl = process.env.LODESTAR_SERVER_URL?.replace(/\/$/, "");
const apiKey = process.env.LODESTAR_API_KEY;
const githubToken = process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;
const prNumber = process.env.PR_NUMBER;
const commitList = (process.env.PR_COMMITS ?? "").split("\n").filter(Boolean);

if (!serverUrl || !apiKey || !githubToken || !repo || !prNumber) {
  console.error("Missing required environment variables");
  process.exit(1);
}

// Read project_id from .lodestar/settings.json if not explicitly set
let projectId = process.env.LODESTAR_PROJECT_ID;
if (!projectId && existsSync(".lodestar/settings.json")) {
  try {
    const settings = JSON.parse(readFileSync(".lodestar/settings.json", "utf-8"));
    projectId = settings.project_id;
  } catch {
    // ignore
  }
}
if (!projectId) {
  projectId = repo.split("/")[1]; // fall back to repo name
}

async function fetchAtom(commitHash) {
  try {
    const res = await fetch(
      `${serverUrl}/projects/${encodeURIComponent(projectId)}/commit/${commitHash}`,
      { headers: { "X-Lodestar-Key": apiKey } }
    );
    if (res.status === 404) return null;
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

function confidenceBadge(confidence) {
  if (confidence === "high") return "🟢 high";
  if (confidence === "medium") return "🟡 medium";
  return "🔴 low";
}

function formatAtom(atom, shortHash) {
  const decisions = JSON.parse(atom.decisions || "[]");
  const rejected = JSON.parse(atom.rejected_alternatives || "[]");
  const files = JSON.parse(atom.files_affected || "[]");
  const aiUsage = JSON.parse(atom.ai_usage || "{}");
  const totalTokens = (aiUsage.input_tokens ?? 0) + (aiUsage.output_tokens ?? 0);
  const models = (aiUsage.models ?? []).join(", ") || aiUsage.model || "unknown";

  const lines = [];

  lines.push(`### \`${shortHash}\` — ${atom.intent}`);
  lines.push("");

  if (decisions.length > 0) {
    lines.push("**Decisions**");
    for (const d of decisions) {
      lines.push(`- **${d.decision}** — ${d.rationale}`);
      if (d.future_note) {
        lines.push(`  > ⚑ ${d.future_note}`);
      }
    }
    lines.push("");
  }

  if (rejected.length > 0) {
    lines.push("<details><summary>Rejected alternatives</summary>");
    lines.push("");
    for (const r of rejected) {
      lines.push(`- ~~${r.option}~~ — ${r.reason}`);
    }
    lines.push("</details>");
    lines.push("");
  }

  const metaParts = [`${confidenceBadge(atom.confidence)} confidence`];
  if (atom.confidence_reason) metaParts.push(`*${atom.confidence_reason}*`);
  lines.push(metaParts.join(" · "));
  lines.push("");

  const usageParts = [`\`${models}\``];
  if (totalTokens > 0) usageParts.push(`${totalTokens.toLocaleString()} tokens`);
  if (aiUsage.turns) usageParts.push(`${aiUsage.turns} turns`);
  if (files.length > 0) usageParts.push(`files: ${files.map(f => `\`${f}\``).join(", ")}`);
  lines.push(`<sub>${usageParts.join(" · ")}</sub>`);

  return lines.join("\n");
}

async function buildComment(atoms) {
  const lines = [
    COMMENT_MARKER,
    "## 🔭 Lodestar AI Audit",
    "",
    `*Captured AI session intelligence for ${atoms.length} commit${atoms.length === 1 ? "" : "s"} in this PR.*`,
    "",
    "---",
    "",
  ];

  for (const { hash, atom } of atoms) {
    lines.push(formatAtom(atom, hash.slice(0, 7)));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push(
    `<sub>Generated by [Lodestar](https://github.com/lodestar-dev/lodestar) · ${new Date().toUTCString()}</sub>`
  );

  return lines.join("\n");
}

async function findExistingComment() {
  const res = await fetch(
    `https://api.github.com/repos/${repo}/issues/${prNumber}/comments?per_page=100`,
    { headers: { Authorization: `Bearer ${githubToken}`, "X-GitHub-Api-Version": "2022-11-28" } }
  );
  if (!res.ok) return null;
  const comments = await res.json();
  return comments.find((c) => c.body?.includes(COMMENT_MARKER)) ?? null;
}

async function postOrUpdateComment(body) {
  const existing = await findExistingComment();
  const url = existing
    ? `https://api.github.com/repos/${repo}/issues/comments/${existing.id}`
    : `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;
  const method = existing ? "PATCH" : "POST";

  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${githubToken}`,
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({ body }),
  });

  if (!res.ok) {
    const err = await res.text();
    console.error("Failed to post comment:", res.status, err);
    process.exit(1);
  }

  console.log(existing ? "Updated existing Lodestar comment" : "Posted new Lodestar comment");
}

// Main
const results = await Promise.all(
  commitList.map(async (hash) => ({ hash, atom: await fetchAtom(hash) }))
);

const found = results.filter((r) => r.atom !== null);

if (found.length === 0) {
  console.log("No Lodestar atoms found for commits in this PR — skipping comment.");
  process.exit(0);
}

const body = await buildComment(found);
await postOrUpdateComment(body);
